run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters:
  enable:
    - errcheck
    - gofumpt
    - govet
    - gocritic
    - misspell
    - prealloc
    - exportloopref
    # depguard intentionally NOT enabled at root; core is linted separately

linters-settings:
  gofumpt:
    extra-rules: true
  errcheck:
    exclude-functions:
      - fmt.Fprint
      - fmt.Fprintf
      - fmt.Fprintln
      - os.Remove
      - (*bufio.Writer).Flush

issues:
  exclude-use-default: false
  exclude-rules:
    # keep tests linted, but silence rare typecheck flakiness
    - path: _test\.go$
      linters: [typecheck]
  exclude-dirs:
    - core
