run:
  timeout: 5m
  issues-exit-code: 1

linters:
  enable:
    - depguard
    - gofumpt
    - govet
    - gocritic
    - misspell
    - prealloc
    - exportloopref

issues:
  exclude-rules:
    - path: _test\.go$
      linters:
        - typecheck

linters-settings:
  gofumpt:
    extra-rules: true

  depguard:
    rules:
      # Enforce app hygiene (runs on repo root; excludes core/)
      app-hygiene:
        files:
          - "**/*.go"
          - "!core/**"
        allow:
          - $gostd
          - "^ipcr-core/"
          - "^ipcr/"
          - "^github.com/"
          - "^golang.org/"
          - "^gopkg.in/"
        deny:
          - pkg: "^ipcr/internal/(engine|primer|probe|oligo|fasta)(/|$)"
            desc: "use ipcr-core/* instead of ipcr/internal/*"

      # Enforce boundary when linting the repo root (targets core/ files)
      core-boundary:
        files:
          - "core/**"
        allow:
          - $gostd
          - "^ipcr-core/"
          - "^github.com/"
          - "^golang.org/"
          - "^gopkg.in/"
        deny:
          - pkg: "^ipcr(/|$)"
            desc: "ipcr-core must not import app-side packages (ipcr/*)"

issues:
  exclude-use-default: false
