run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - core   # linted in a separate job with its own config

linters:
  enable:
    - depguard
    - errcheck
    - gofumpt
    - govet
    - gocritic
    - misspell
    - prealloc
    - exportloopref

linters-settings:
  gofumpt:
    extra-rules: true

  # Only keep a boundary rule here if you really need one for root code.
  # (Core has its own config; root should NOT police core/.)
  depguard:
    rules: {}

  errcheck:
    exclude-functions:
      - fmt.Fprint
      - fmt.Fprintf
      - fmt.Fprintln
      - os.Remove
      - (*bufio.Writer).Flush

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go$
      linters: [typecheck]
