# .golangci.yml
run:
  timeout: 5m
  issues-exit-code: 1

linters:
  enable:
    - depguard
    - gofumpt
    - govet
    - gocritic
    - misspell
    - prealloc
    - exportloopref

linters-settings:
  gofumpt:
    extra-rules: true

  depguard:
    rules:
      # Core must NOT depend on the app module.
      core-boundary:
        packages:
          - "^ipcr-core(/|$)"
        deny:
          - pkg: "^ipcr(/|$)"
            desc: "ipcr-core must not import app-side packages (ipcr/*)"
        allow:
          - $gostd
          - "^ipcr-core/"
          - "^github.com/"
          - "^golang.org/"
          - "^gopkg.in/"

      # App must NOT import the old, now-deleted internals for engine/primer/oligo/probe/fasta.
      app-hygiene:
        packages:
          - "^ipcr(/|$)"
        deny:
          - pkg: "^ipcr/internal/(engine|primer|probe|oligo|fasta)(/|$)"
            desc: "use ipcr-core/* instead of ipcr/internal/*"
        allow:
          - $gostd
          - "^ipcr-core/"
          - "^ipcr/internal/"   # allow other internal packages in this repo
          - "^github.com/"
          - "^golang.org/"
          - "^gopkg.in/"

issues:
  exclude-use-default: false
