// core/engine/seed.go
package engine

import "ipcr-core/primer"

// ---- Seeds & AC automaton --------------------------------------------------

// SeedPayload describes one primer orientation that can be generated by a
// concrete seed pattern. Multiple primer orientations may share the same
// pattern, especially after approximate seed-neighborhood expansion.
type SeedPayload struct {
	PairIdx    int
	Which      byte // 'A','B','a','b'
	PrimerLen  int
	SeedOffset int
}

// SeedPattern is one unique concrete A/C/G/T seed pattern plus every primer
// orientation payload associated with that pattern. The AC automaton is built
// over SeedPattern.Pat, not over every payload separately.
type SeedPattern struct {
	Pat      []byte
	Payloads []SeedPayload
}

// EncodedSeed is a compact 2-bit key for A/C/G/T seed patterns up to 32 bp.
// It avoids allocating temporary strings while deduplicating seed patterns
// during approximate seed-neighborhood construction.
type EncodedSeed struct {
	Code uint64
	Len  uint8
}

func encodeSeedPattern(p []byte) (EncodedSeed, bool) {
	if len(p) == 0 || len(p) > 32 {
		return EncodedSeed{}, false
	}

	var code uint64
	for _, b := range p {
		var v uint64
		switch b {
		case 'A':
			v = 0
		case 'C':
			v = 1
		case 'G':
			v = 2
		case 'T':
			v = 3
		default:
			return EncodedSeed{}, false
		}
		code = (code << 2) | v
	}
	return EncodedSeed{Code: code, Len: uint8(len(p))}, true
}

func decodeSeedPattern(k EncodedSeed) []byte {
	if k.Len == 0 {
		return nil
	}

	out := make([]byte, int(k.Len))
	for i := int(k.Len) - 1; i >= 0; i-- {
		switch k.Code & 3 {
		case 0:
			out[i] = 'A'
		case 1:
			out[i] = 'C'
		case 2:
			out[i] = 'G'
		case 3:
			out[i] = 'T'
		}
		k.Code >>= 2
	}
	return out
}

// Seed is the legacy flattened seed representation returned by BuildSeeds.
// Internal compiled-panel scanning uses SeedPattern/SeedPayload to deduplicate
// repeated concrete seed strings.
type Seed struct {
	PairIdx    int
	Which      byte // 'A','B','a','b'
	Pat        []byte
	PrimerLen  int
	SeedOffset int
}

const (
	// ApproxSeedMaxVariantsPerOrientation bounds approximate seed-neighborhood
	// expansion for one primer orientation. Orientations whose variant set exceeds
	// this cap fall back to the brute-force verifier without disabling seeding for
	// the rest of the panel.
	ApproxSeedMaxVariantsPerOrientation = 50000
)

var seedAlphabet = [...]byte{'A', 'C', 'G', 'T'}

// configuredSeedLen returns the configured seed length before mismatch-model
// constraints are applied. cfg == 0 means auto (min(12, primerLen)).
func configuredSeedLen(primerLen, cfg int) int {
	if cfg <= 0 {
		if primerLen < 12 {
			return primerLen
		}
		return 12
	}
	if cfg > primerLen {
		return primerLen
	}
	return cfg
}

// BuildSeeds builds flattened seed payloads for all primer orientations.
//
// The return shape is kept for compatibility with older tests/callers. Internal
// compiled-panel scanning uses buildSeedPatterns so duplicate concrete seed
// patterns are stored once in the automaton with multiple payloads.
func BuildSeeds(pairs []primer.Pair, seedLen, terminalWindow int) (seeds []Seed, has map[int]map[byte]bool) {
	return buildSeeds(pairs, seedLen, terminalWindow, 0)
}

func buildSeeds(pairs []primer.Pair, seedLen, terminalWindow, maxMM int) (seeds []Seed, has map[int]map[byte]bool) {
	patterns, has := buildSeedPatterns(pairs, seedLen, terminalWindow, maxMM)
	return flattenSeedPatterns(patterns), has
}

func flattenSeedPatterns(patterns []SeedPattern) []Seed {
	var n int
	for _, pattern := range patterns {
		n += len(pattern.Payloads)
	}

	seeds := make([]Seed, 0, n)
	for _, pattern := range patterns {
		for _, payload := range pattern.Payloads {
			seeds = append(seeds, Seed{
				PairIdx:    payload.PairIdx,
				Which:      payload.Which,
				Pat:        append([]byte(nil), pattern.Pat...),
				PrimerLen:  payload.PrimerLen,
				SeedOffset: payload.SeedOffset,
			})
		}
	}
	return seeds
}

func buildSeedPatterns(pairs []primer.Pair, seedLen, terminalWindow, maxMM int) (patterns []SeedPattern, has map[int]map[byte]bool) {
	builder := newSeedPatternBuilder(4 * len(pairs))
	has = make(map[int]map[byte]bool, len(pairs))

	if seedLen < 0 {
		// No seeds: 'has' stays empty, SimulateCompiled will fallback for all orientations.
		return nil, has
	}

	mark := func(i int, w byte) {
		m, ok := has[i]
		if !ok {
			m = make(map[byte]bool, 4)
			has[i] = m
		}
		m[w] = true
	}

	addOrientation := func(pairIdx int, which byte, pat []byte, preferRight bool, leftTW, rightTW int) {
		if len(pat) == 0 {
			return
		}

		off, sl, ok := chooseSeedSpan(pat, seedLen, preferRight)
		if !ok {
			return
		}

		variants := make([][]byte, 0, 1)
		ok = enumerateSeedVariants(
			pat[off:off+sl], off, len(pat), maxMM, leftTW, rightTW,
			ApproxSeedMaxVariantsPerOrientation,
			func(seed []byte) {
				variants = append(variants, seed)
			},
		)
		if !ok || len(variants) == 0 {
			// Variant explosion or no legal concrete seed. Fall back for this
			// orientation rather than risking false negatives.
			return
		}

		payload := SeedPayload{
			PairIdx:    pairIdx,
			Which:      which,
			PrimerLen:  len(pat),
			SeedOffset: off,
		}
		added := false
		for _, seed := range variants {
			if !builder.add(seed, payload) {
				// Seed patterns longer than 32 bp cannot use the compact 2-bit key.
				// Fall back for this orientation rather than introducing partial
				// seed coverage that could create false negatives.
				return
			}
			added = true
		}
		if added {
			mark(pairIdx, which)
		}
	}

	for i, p := range pairs {
		a := []byte(p.Forward)
		b := []byte(p.Reverse)
		ra := primer.RevComp(a)
		rb := primer.RevComp(b)

		// Forward primer orientations: protect the 3' end via rightTW.
		addOrientation(i, 'A', a, true, 0, terminalWindow)
		addOrientation(i, 'B', b, true, 0, terminalWindow)

		// Reverse-complement orientations are scanned on the forward genomic
		// strand, so the original primer's 3' end is the left side of rc(primer).
		addOrientation(i, 'a', ra, false, terminalWindow, 0)
		addOrientation(i, 'b', rb, false, terminalWindow, 0)
	}
	return builder.patterns, has
}

type seedPatternBuilder struct {
	patterns  []SeedPattern
	byEncoded map[EncodedSeed]int
}

func newSeedPatternBuilder(capacity int) *seedPatternBuilder {
	return &seedPatternBuilder{
		patterns:  make([]SeedPattern, 0, capacity),
		byEncoded: make(map[EncodedSeed]int, capacity),
	}
}

func (b *seedPatternBuilder) add(pat []byte, payload SeedPayload) bool {
	key, ok := encodeSeedPattern(pat)
	if !ok {
		return false
	}
	idx, ok := b.byEncoded[key]
	if !ok {
		idx = len(b.patterns)
		b.byEncoded[key] = idx
		b.patterns = append(b.patterns, SeedPattern{Pat: decodeSeedPattern(key)})
	}
	b.patterns[idx].Payloads = append(b.patterns[idx].Payloads, payload)
	return true
}

func chooseSeedSpan(pat []byte, seedLen int, preferRight bool) (offset, length int, ok bool) {
	length = configuredSeedLen(len(pat), seedLen)
	if length <= 0 || length > len(pat) {
		return 0, 0, false
	}

	bestOffset := 0
	bestScore := uint64(0)
	for off := 0; off <= len(pat)-length; off++ {
		score := exactVariantEstimate(pat[off : off+length])
		if off == 0 || score < bestScore || (score == bestScore && seedTieBreak(off, bestOffset, preferRight)) {
			bestOffset = off
			bestScore = score
		}
	}
	return bestOffset, length, true
}

func seedTieBreak(candidate, current int, preferRight bool) bool {
	if preferRight {
		return candidate > current
	}
	return candidate < current
}

func exactVariantEstimate(seed []byte) uint64 {
	var score uint64 = 1
	for _, p := range seed {
		var n uint64
		for _, b := range seedAlphabet {
			if primer.BaseMatch(b, p) {
				n++
			}
		}
		if n == 0 {
			// Invalid primer symbols should have been rejected upstream. Treating
			// them as expensive makes valid spans win if any exist.
			n = 5
		}
		score *= n
	}
	return score
}

func enumerateSeedVariants(
	seed []byte,
	seedOffset int,
	primerLen int,
	maxMM int,
	leftTW int,
	rightTW int,
	maxVariants int,
	emit func([]byte),
) bool {
	if len(seed) == 0 || emit == nil || maxVariants <= 0 {
		return false
	}
	if maxMM < 0 {
		maxMM = 0
	}
	if leftTW < 0 {
		leftTW = 0
	}
	if rightTW < 0 {
		rightTW = 0
	}

	buf := make([]byte, len(seed))
	emitted := 0
	ok := true

	var walk func(pos, mm int)
	walk = func(pos, mm int) {
		if !ok || mm > maxMM {
			return
		}
		if pos == len(seed) {
			if emitted >= maxVariants {
				ok = false
				return
			}
			out := append([]byte(nil), buf...)
			emit(out)
			emitted++
			return
		}

		fullIdx := seedOffset + pos
		protected := (leftTW > 0 && fullIdx < leftTW) || (rightTW > 0 && fullIdx >= primerLen-rightTW)
		for _, b := range seedAlphabet {
			cost := 0
			if !primer.BaseMatch(b, seed[pos]) {
				cost = 1
			}
			if protected && cost != 0 {
				continue
			}
			if mm+cost > maxMM {
				continue
			}
			buf[pos] = b
			walk(pos+1, mm+cost)
		}
	}

	walk(0, 0)
	return ok && emitted > 0
}
