# core/.golangci.yml  (REPLACE)
run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters:
  enable:
    # depguard disabled in core to stop false-positives on ipcr-core/*
    - errcheck
    - gofumpt
    - govet
    - gocritic
    - misspell
    - prealloc
    - exportloopref

linters-settings:
  gofumpt:
    extra-rules: true
  errcheck:
    exclude-functions:
      - fmt.Fprint
      - fmt.Fprintf
      - fmt.Fprintln
      - os.Remove
      - (*bufio.Writer).Flush

issues:
  exclude-use-default: false
