run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters:
  enable:
    - depguard
    - errcheck
    - gofumpt
    - govet
    - gocritic
    - misspell
    - prealloc
    - exportloopref

linters-settings:
  gofumpt:
    extra-rules: true
  depguard:
    rules:
      core-boundary:
        files: ["**/*.go"]
        allow:
          - $gostd
          - "^ipcr-core/"
          - "^github.com/"
          - "^golang.org/"
          - "^gopkg.in/"
        deny:
          - pkg: "^ipcr(/|$)"
            desc: "ipcr-core must not import app-side packages (ipcr/*)"
  errcheck:
    exclude-functions:
      - fmt.Fprint
      - fmt.Fprintf
      - fmt.Fprintln
      - os.Remove
      - (*bufio.Writer).Flush

issues:
  exclude-use-default: false
